/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mantis.dianreenvio;

import BaseDatos.ConexionManager;
import BaseDatos.ServerMantisSQL;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Charly Cimino
 */
public class ActualizarEstadoCorreo extends javax.swing.JDialog {
   ServerMantisSQL con = new ServerMantisSQL();
    List<String> listaEmailId = new ArrayList<>();
    static String Auto = "N";

    public ActualizarEstadoCorreo(java.awt.Frame parent, boolean modal, String pauto) {
        super(parent, modal);
        Auto = pauto;
        initComponents();

        // Fecha actual
        Date hoy = new Date();

// Asignar a los datepickers
        iFacFec.setDate(hoy);
        fFacFec.setDate(hoy);

        if (Auto.equalsIgnoreCase("S")) {
            cargarestadoCorreo();
            enviobloquesestado();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        correos = new javax.swing.JTextArea();
        iFacFec = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fFacFec = new com.toedter.calendar.JDateChooser();
        eFacNro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NitIde = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        contadorenviados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Actualizando estado de correos");

        correos.setEditable(false);
        correos.setBackground(new java.awt.Color(241, 241, 241));
        correos.setColumns(20);
        correos.setForeground(new java.awt.Color(102, 102, 102));
        correos.setRows(5);
        jScrollPane1.setViewportView(correos);

        iFacFec.setDateFormatString("yyyy-MM-dd");

        jLabel2.setText("Desde");

        jLabel3.setText("Hasta");

        fFacFec.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Numero");

        jLabel7.setText("Cliente");

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        contadorenviados.setText("Documentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iFacFec, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(fFacFec, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eFacNro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NitIde, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(contadorenviados))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iFacFec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fFacFec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eFacNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NitIde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(contadorenviados)
                .addGap(2, 2, 2)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarestadoCorreo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        enviobloquesestado();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void enviobloquesestadoant() {

        SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {

            @Override
            protected Void doInBackground() throws Exception {

                SwingUtilities.invokeLater(() -> {
                    jButton2.setEnabled(false);
                    jButton1.setEnabled(false);
                });

                List<JSONObject> bloques = generarJsonPorBloques(listaEmailId, 1);

                int total = bloques.size();

                SwingUtilities.invokeLater(() -> {
                    progressBar.setMaximum(total);
                    progressBar.setValue(0);
                    progressBar.setStringPainted(true);
                });

                AtomicInteger enviados = new AtomicInteger(0);

                // Pool de 4 hilos
                ExecutorService executor = Executors.newFixedThreadPool(4);

                List<Future<?>> tareas = new ArrayList<>();

                for (JSONObject jsonEnvio : bloques) {

                    tareas.add(executor.submit(() -> {

                        try {

                            enviarCorreosTracking(jsonEnvio.toString());

                            int count = enviados.incrementAndGet();

                            publish(count);

                        } catch (Exception ex) {

                            SwingUtilities.invokeLater(()
                                    -> contadorenviados.setText("Error envío: " + ex.getMessage())
                            );
                        }

                    }));
                }

                // esperar a que terminen todos
                for (Future<?> f : tareas) {
                    f.get();
                }

                executor.shutdown();

                return null;
            }

            @Override
            protected void process(List<Integer> chunks) {

                int value = chunks.get(chunks.size() - 1);

                progressBar.setValue(value);

                contadorenviados.setText(
                        "Bloques enviados: " + value + " / " + progressBar.getMaximum()
                );
            }

            @Override
            protected void done() {

                jButton2.setEnabled(true);
                jButton1.setEnabled(true);

                contadorenviados.setText("Envío finalizado");

                dispose();
            }
        };

        worker.execute();
    }

    public void enviobloquesestado() {

        SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {

            @Override
            protected Void doInBackground() throws Exception {
                jButton2.setEnabled(false);
                jButton1.setEnabled(false);
                int count = 0;
                List<JSONObject> bloques = generarJsonPorBloques2(listaEmailId, 100);

                progressBar.setMaximum(bloques.size());
                progressBar.setStringPainted(true);
                for (JSONObject jsonEnvio : bloques) {
                    try {

                        /// enviarCorreosTracking(jsonEnvio.toString());
                         actualizarestadotracking(jsonEnvio.toString());
                        count++;

                        publish(count); // envía progreso al UI

                    } catch (Exception ex) {

                        contadorenviados.setText("Error envío: " + ex.getMessage());

                    }
                }

                return null;
            }

            @Override
            protected void process(List<Integer> chunks) {

                int value = chunks.get(chunks.size() - 1);

                progressBar.setValue(value);

                contadorenviados.setText(
                        "Bloques enviados: " + value + " / " + progressBar.getMaximum()
                );
            }

            @Override
            protected void done() {
                jButton2.setEnabled(true);
                jButton1.setEnabled(true);
                contadorenviados.setText("Envío finalizado");
                dispose();

            }
        };

        worker.execute();
    }

    private void actualizarestadotracking(String jsonBody) {
        try {
            String endpoint = "https://api.smtp2go.com/v3/email/search";
            URL url = new URL(endpoint);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setRequestProperty("X-Smtp2go-Api-Key", "api-991E817E7E38462481E3EC5BFB6CABC9");

            conn.setDoOutput(true);
            System.out.println("url: " + url.toString());
            System.out.println("jsonBody: " + jsonBody);

            try (OutputStream os = conn.getOutputStream()) {
                os.write(jsonBody.getBytes(StandardCharsets.UTF_8));
                os.flush();
            }

            int responseCode = conn.getResponseCode();

            InputStream is = (responseCode >= 200 && responseCode < 300)
                    ? conn.getInputStream()
                    : conn.getErrorStream();

            String response;
            try (BufferedReader br = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8))) {
                response = br.lines().collect(Collectors.joining());
            }

            conn.disconnect();

            String bonito;
            if (response.trim().startsWith("[")) {
                JSONArray jsonArray = new JSONArray(response);
                bonito = jsonArray.toString(4);
            } else {
                JSONObject jsonObject = new JSONObject(response);
                bonito = jsonObject.toString(4);
            }

            JSONObject json = new JSONObject(response);

// entrar al nodo data
            JSONObject data = json.getJSONObject("data");

// obtener array emails
            JSONArray emails = data.getJSONArray("emails");

            for (int i = 0; i < emails.length(); i++) {

                JSONObject email = emails.getJSONObject(i);
                actualizarestado(email);
                //  System.out.println("url: " + bonito);
            }

        } catch (Exception e) {

        }
    }

    public void actualizarestado(JSONObject email) {
        String email_id = email.optString("email_id");
        String process_status = email.optString("process_status");
        String recipient = email.optString("recipient");
        String status = email.optString("status");
        String responseMail = email.optString("response");

        // traducir estado
        String estadoTraducido = traducirEstado(status);

        System.out.println("ID: " + email_id);
        System.out.println("Process: " + process_status);
        System.out.println("Recipient: " + recipient);
        System.out.println("Status: " + estadoTraducido);
        System.out.println("Response: " + responseMail);
        System.out.println("----------------------");
        String responseLimpio = limpiarSQL(responseMail);
        String update = "update Factura set FacTrackCorEst = '"+estadoTraducido+"', FacObsEnvEle = '"+responseLimpio+"' where FacOrdTraSec = '"+email_id+"' and "
                + " FacTrackCorEst not in ('Entregado','Abierto','Rebotado','Rechazado','Cancelado','Aplazado')  ";
    
        
        // guardar completed
        if ("completed".equalsIgnoreCase(process_status)) {
            //istaCompleted.add(email);
            con.sqlExec(update);
        } else {
            // posibles candidatos si NO hay completed
            if (!"submission".equalsIgnoreCase(status)
                    && recipient != null
                    && !recipient.trim().isEmpty()) {
            con.sqlExec(update);
                //listaFinal.add(email);
            }
        }
        
    }
    
   
    public static String limpiarSQL(String texto) {
    if (texto == null) return "";

    return texto
            .replace("'", "''")     // escapar comillas simples
            .replace("\n", " ")     // quitar saltos de línea
            .replace("\r", " ")
            .replace("\t", " ")
            .trim();
}
    
    
    
    public String traducirEstado(String estado) {

        if (estado == null) {
            return "Pendiente";
        }

        String e = estado.toLowerCase();

        switch (e) {
            case "processed":
                return "Procesado";

            case "delivered":
                return "Entregado";

            case "unsubscribed":
                return "Desuscrito";

            case "spam":
                return "Marcado como spam";

            case "deferred":
                return "Diferido";

            case "opened":
                return "Abierto";

            case "refused":
            case "rejected":
                return "Rechazado";

            case "cancelled":
                return "Cancelado";

            case "defer":
                return "Aplazado";

            default:
                if (e.contains("bounce")) {
                    return "Rebotado";
                }
                return "Pendiente";
        }
    }

    private void enviarCorreosTracking(String jsonBody) throws Exception {
        String endpoint = "http://169.46.48.131:8087/MantisWebServices/rest/pConsultarEstadoCorreoApi";
        URL url = new URL(endpoint);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setDoOutput(true);
        System.out.println("url: " + url.toString());
        // JSON Body

        //JSONObject jsonBody = new JSONObject();
        //jsonBody.put("SDTEstadosCorreoApi", json);
        try (OutputStream os = conn.getOutputStream()) {
            os.write(jsonBody.getBytes(StandardCharsets.UTF_8));
            os.flush();
        }

        int responseCode = conn.getResponseCode();

        InputStream is = (responseCode >= 200 && responseCode < 300)
                ? conn.getInputStream()
                : conn.getErrorStream();

        String response;
        try (BufferedReader br = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8))) {
            response = br.lines().collect(Collectors.joining());
        }

        conn.disconnect();

        String bonito;
        if (response.trim().startsWith("[")) {
            JSONArray jsonArray = new JSONArray(response);
            bonito = jsonArray.toString(4);
        } else {
            JSONObject jsonObject = new JSONObject(response);
            bonito = jsonObject.toString(4);
        }

        //TXTresponse.setText(bonito);
        //procesarRespuesta(response, numeroFactura);
    }

    public void cargarestadoCorreo() {
        listaEmailId.clear();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaIni = sdf.format(iFacFec.getDate());
        String fechaFin = sdf.format(fFacFec.getDate());
        String sql = "SET DATEFORMAT ymd; Select FacNro,FacSec, FacOrdTraSec, FacFec as Fecha "
                + " FROM factura f WITH (NOLOCK) "
                + " LEFT JOIN tipos t\n"
                + " ON f.factipcod = t.tipcod\n"
                + " LEFT JOIN clientes cli\n"
                + " ON f.FacNitSec = cli.NitSec\n"
                + " AND f.FacCliSec = cli.CliSec\n"
                + " LEFT JOIN Nit n\n"
                + " ON f.FacNitSec = n.NitSec\n"
                + " WHERE\n"
                + " FacEleStatus = 'S' and (facordtrasec IS NOT NULL AND facordtrasec <> '') and  "
                + " (FacTrackCorEst not in ('Entregado','Abierto','Rebotado','Rechazado','Cancelado','Aplazado') ) "
                + " AND ( not FacOrdTraSec = '' and not FacOrdTraSec is null) "
                + " and f.FacEst = 'A'\n"
                + " AND f.FacFecTra <= DATEADD(MINUTE,-5,GETDATE())\n"
                + " AND f.FacFec >= '" + fechaIni + "' "
                + " AND f.FacFec <= '" + fechaFin + "' "
                + " AND n.NitIde LIKE '%" + NitIde.getText().toString() + "%' "
                + " AND FacNro like '%" + eFacNro.getText().toString() + "%'"
                + " ORDER BY Fecha DESC  ";
        System.out.println(sql);
        int contadodoc = 0;
        try (Connection con = ConexionManager.getInstancia().getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                contadodoc += 1;
                String facSec = rs.getString("FacSec");
                String facNro = rs.getString("FacNro");

                //String track = rs.getString("FacTrackCorEst");
                String emailId = rs.getString("FacOrdTraSec");
                // String envio = rs.getString("FacEleEnvCor");
                JSONObject factura = new JSONObject();
                factura.put("FacSec", facSec);
                factura.put("FacNro", facNro);

                listaEmailId.add(emailId);

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        String bloquesjson = "";
        List<JSONObject> bloques = generarJsonPorBloques(listaEmailId, 1);
        int contadorbloques = 0;
        for (JSONObject jsonEnvio : bloques) {
            contadorbloques += 1;
            bloquesjson += jsonEnvio.toString(4) + "\n";
        }
        contadorenviados.setText("Bloques: " + contadorbloques + ", Total documentos: " + contadodoc);
        correos.setText(bloquesjson);

    }

    private List<JSONObject> generarJsonPorBloques(List<String> emails, int tamanio) {

        List<JSONObject> listaJson = new ArrayList<>();

        for (int i = 0; i < emails.size(); i += tamanio) {

            JSONArray emailArray = new JSONArray();

            int fin = Math.min(i + tamanio, emails.size());

            for (int j = i; j < fin; j++) {
                emailArray.put(emails.get(j));
            }

            JSONObject data = new JSONObject();
            data.put("ignore_case", false);
            data.put("email_id", emailArray);
            data.put("opened_only", false);
            data.put("filter_query", JSONObject.NULL);
            data.put("status_counts", false);
            data.put("clicked_only", false);

            JSONObject root = new JSONObject();
            root.put("SDTEstadosCorreoApi", data);

            listaJson.add(root);
        }

        return listaJson;
    }

    private List<JSONObject> generarJsonPorBloques2(List<String> emails, int tamanio) {

        List<JSONObject> listaJson = new ArrayList<>();

        for (int i = 0; i < emails.size(); i += tamanio) {

            JSONArray emailArray = new JSONArray();

            int fin = Math.min(i + tamanio, emails.size());

            for (int j = i; j < fin; j++) {
                emailArray.put(emails.get(j));
            }

            JSONObject data = new JSONObject();
            data.put("ignore_case", false);
            data.put("email_id", emailArray);
            data.put("opened_only", false);
            data.put("filter_query", JSONObject.NULL);
            data.put("status_counts", false);
            data.put("clicked_only", false);

            /*JSONObject root = new JSONObject();
            root.put("SDTEstadosCorreoApi", data);*/
            listaJson.add(data);
        }

        return listaJson;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarEstadoCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarEstadoCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarEstadoCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarEstadoCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarEstadoCorreo dialog = new ActualizarEstadoCorreo(new javax.swing.JFrame(), true, Auto);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NitIde;
    private javax.swing.JLabel contadorenviados;
    private javax.swing.JTextArea correos;
    private javax.swing.JTextField eFacNro;
    private com.toedter.calendar.JDateChooser fFacFec;
    private com.toedter.calendar.JDateChooser iFacFec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
