/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mantis.dianreenvio;

import BaseDatos.ServerMantisSQL;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Charly Cimino
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
        CargarConf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CadenaServidor = new javax.swing.JTextField();
        GuardarConexion = new javax.swing.JButton();
        UrlwebServices = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        benvioauto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel1.setText("Cadena servidor");

        CadenaServidor.setBackground(new java.awt.Color(242, 244, 246));
        CadenaServidor.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        CadenaServidor.setActionCommand("<Not Set>");
        CadenaServidor.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        CadenaServidor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        GuardarConexion.setBackground(new java.awt.Color(0, 153, 255));
        GuardarConexion.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        GuardarConexion.setForeground(new java.awt.Color(255, 255, 255));
        GuardarConexion.setText("Guardar conexión");
        GuardarConexion.setBorderPainted(false);
        GuardarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarConexionActionPerformed(evt);
            }
        });

        UrlwebServices.setBackground(new java.awt.Color(242, 244, 246));
        UrlwebServices.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        UrlwebServices.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        UrlwebServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrlwebServicesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel3.setText("URL Web services");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setText("Automatico");

        benvioauto.setText("Envio automatico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadenaServidor)
                    .addComponent(UrlwebServices)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 756, Short.MAX_VALUE)
                        .addComponent(GuardarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(benvioauto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(UrlwebServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(CadenaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(benvioauto)
                .addGap(7, 7, 7)
                .addComponent(GuardarConexion)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UrlwebServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrlwebServicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UrlwebServicesActionPerformed

    private void GuardarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarConexionActionPerformed

        String rutaserver = "C:\\DianReenvio\\ConexionServer.txt";
        String rutaURL = "C:\\DianReenvio\\UrlServidor.txt";
        String rutalocal = "C:\\DianReenvio\\envioauto.txt";

        String envioauto = "N";

        if (benvioauto.isSelected()) {
            envioauto = "S";
        }

        String Cadenaserverstr = CadenaServidor.getText().toString().trim();
        String URLstr = UrlwebServices.getText().toString().trim();
        Connection connection;
        try {

            Files.write(Paths.get(rutalocal), envioauto.getBytes(Charset.forName("UTF-8")));
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ok15.png")));

        } catch (IOException ex) {
            System.out.println("Error: " + ex.getMessage());
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/error15.png")));
        }
        try {
            if (netIsAvailable(URLstr) == true) {
                Files.write(Paths.get(rutaURL), URLstr.getBytes(Charset.forName("UTF-8")));
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ok15.png")));
            } else {
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/error15.png")));
            }

        } catch (IOException ex) {
            System.out.println("Error: " + ex.getMessage());
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/error15.png")));
        }

        try {

            connection = DriverManager.getConnection(Cadenaserverstr);
            if (VerificarConexion(connection)) {
                Files.write(Paths.get(rutaserver), Cadenaserverstr.getBytes(Charset.forName("UTF-8")));
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ok15.png")));
            } else {
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/error15.png")));
            }

        } catch (SQLException ex) {

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/error15.png")));
        } catch (IOException ex) {

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/error15.png")));
        }
    }//GEN-LAST:event_GuardarConexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    private void CargarConf() {

        String Ruta = "C:\\DianReenvio\\";
 String rutalocal = "C:\\DianReenvio\\envioauto.txt";
        String rutaserver = "C:\\DianReenvio\\ConexionServer.txt";
        String rutaURL = "C:\\DianReenvio\\UrlServidor.txt";

        File carpeta = new File(Ruta);
        File crutaserver = new File(rutaserver);
        File cRutaURL = new File(rutaURL);

        try {
            if (!carpeta.exists()) {
                if (carpeta.mkdirs()) {
                } else {
                    System.out.println("No se pudo crear la carpeta.");
                }
            } else {
                System.out.println("La carpeta ya existe.");
            }

            if (!crutaserver.exists()) {
                crutaserver.createNewFile();
            } else {
                System.out.println("La carpeta ya existe.");
            }

// Declarar una variable BufferedReader
            BufferedReader br = null;
            try {
                br = new BufferedReader(new FileReader(rutaserver));
                String texto = br.readLine();
                while (texto != null) {
                    CadenaServidor.setText(texto);
                    texto = br.readLine();
                }

                br = new BufferedReader(new FileReader(rutaURL));
                texto = br.readLine();
                while (texto != null) {
                    UrlwebServices.setText(texto);
                    texto = br.readLine();
                }
                
                     br = new BufferedReader(new FileReader(rutalocal));
                texto = br.readLine();
             
                    
                    if(texto.equalsIgnoreCase("S")){
                        benvioauto.setSelected(true);
                    }
                    

            } // Captura de excepción por fichero no encontrado
            catch (FileNotFoundException ex) {

                ex.printStackTrace();
            } catch (IOException ex) {

            } catch (Exception ex) {

            }

        } catch (IOException ex) {

        }

    }

    public boolean VerificarConexion(Connection con) {
        try {
            return con != null && !con.isClosed();
        } catch (SQLException ignored) {
        }
        return false;
    }

    private static boolean netIsAvailable(String urlStr) {
        try {
            URL url = new URL(urlStr);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setConnectTimeout(5000); // tiempo máximo para conectar
            conn.setReadTimeout(5000);    // tiempo máximo para leer respuesta
            conn.setRequestMethod("HEAD"); // más rápido que GET, solo verifica encabezados
            int responseCode = conn.getResponseCode();
            System.out.println("Código de respuesta: " + responseCode);
            return true;
        } catch (IOException e) {
            // Error de red o el servidor no responde
            System.out.println("Error: " + e.getMessage());
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadenaServidor;
    private javax.swing.JButton GuardarConexion;
    private javax.swing.JTextField UrlwebServices;
    private javax.swing.JCheckBox benvioauto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
